config/routes.rb
Rails.application.routes.draw do

  resources :listings
  get 'pages/about'
   get 'seller' => "listings#seller"
  get 'pages/contact'

  # the page root
  root 'listings#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
    namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
   # mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    #mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :listings
   end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/models/listing.rb
class Listing < ActiveRecord::Base
   mount_uploader :image, ImageUploader

  belongs_to :user
  
end

app/controllers/api/listings_controller.rb
class Api::ListingsController < ApplicationController
 #before_action :set_listing, only: [:show, :edit, :update, :destroy]
 #before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
#before_filter :check_user, only: [:edit, :update, :destroy]

protect_from_forgery with: :null_session
respond_to :json


  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")

  end



def index
    @listings = Listing.all.order("created_at DESC")

  end


def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end


def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end









  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id


    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end
 


 def destroy 
 @listing.destroy
 respond_to do |format|
  format.html { redirect_to listings_url}
  format.json { head :no_content}
 end
end











  private

  def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end


def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
 before_action :set_listing, only: [:show, :edit, :update, :destroy]
 before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
before_filter :check_user, only: [:edit, :update, :destroy]



  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end



def index
    @listings = Listing.all.order("created_at DESC")
  end


def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end


def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end









  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id


    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end
 


 def destroy 
 @listing.destroy
 respond_to do |format|
  format.html { redirect_to listings_url}
  format.json { head :no_content}
 end
end











  private

  def set_listing
      @listing = Listing.find(params[:id])
    end

    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end


def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
     <div class="container">
    
    <%= form_for(@listing, html: { multipart: true}) do |f| %>
      <% if @listing.errors.any? %>
        <div id="error_explanation" 
          <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

          <ul>
          <% @listing.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        

      <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div><br>
  
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div><br>
    <% end %>
    </div>

app/views/listings/edit.html.erb
<div class="container">
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
</div>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Handcrafted items from <br>
      around the world.</h1>
  <h2>Discover one-of-a-kind items</h2>
</div>


<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>







<% if user_signed_in? %>
  <%= link_to "New Listing", new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } %>
<% end %>

app/views/listings/new.html.erb
 <div class='container' </div>
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %> 
</div>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td>
        <%= image_tag listing.image.url(:thumb) %>
      </td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>
    <br>
    
  </div>
</div>



<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>