config/routes.rb
Rails.application.routes.draw do

  resources :listings
  get 'pages/about'
   get 'seller' => "listings#seller"
  get 'pages/contact'

  # the page root
  root 'listings#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
    namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
   # mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    #mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :listings
   end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/views/shared/_flash_notice.html.haml
- if flash[:notice].present? || flash[:alert].present? || flash[:error].present?
  - [:notice, :alert, :error].each do |key|
    - next if flash[key].blank?
    .flash-container
      .flash{class: key}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
        = flash[key]

      - flash[key] = nil

app/views/shared/_languages.html.haml
= link_to_unless_current "En", sessions_path("en")

app/views/shared/_logo.html.haml
.form-group
  %i.fa.fa-star
  Your Buisness Name