config/routes.rb
Rails.application.routes.draw do

  resources :listings
  get 'pages/about'
   get 'seller' => "listings#seller"
  get 'pages/contact'

  # the page root
  root 'listings#index'

  # routes for Devise and Omniauth
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  # routes for Active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # routes for the API's
    namespace :api, defaults: {format: :json} do
    mount TolSkitSessions::Engine => "/"
    mount TolSkitSessionsFacebook::Engine => "sessions/facebook"
   # mount TolSkitSessionsTwitter::Engine => "sessions/twitter"
    #mount TolSkitSessionsInstagram::Engine => "sessions/instagram"
    
    resources :users
    resources :listings
   end

  # routes for locale change
  get 'sessions/:locale', to: "sessions#switch", as: :sessions

  # routes for Users
  resources :users

  # route for User Sign Out
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :signout
  end

  # routes for Omniauth
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

end

app/views/layouts/_footer.html.erb
 <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2016</p>
                </div>
            </div>
        </footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Your Business Name</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="dropdown">
            <% if current_user.provider %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= image_tag current_user.image, class: "img img-circle",style: "width: 50px; height: 50px" %><b class="caret"></b></a>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %><b class="caret"></b></a>
          <% end %>
          <ul class="dropdown-menu">

            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  
  <div class="container">

  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title STARTER-KIT
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    = favicon_link_tag 'favicon.ico'
        
  %body{class: params[:controller].gsub("/", "-")}

    .container-fluid.margin-top-100
      = yield

      %script{type: "text/javascript", 'data-turbolinks-eval'=>false}
        var string = "#{(j (yield :scripts))}";
        eval(string);
        window.starterkitrails.shared.init();
    = render 'shared/flash_notice'

app/views/layouts/mail.html.haml
%html{style: "height: 100%"}
  %head
    %meta{content: "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    %title Email StarterKit
  %body{style: "margin: 0; padding: 0; height: 100%; background-color: white"}
    %table{cellpadding: "0", cellspacing: "0", style: "width: 100%; height: 100%; border-spacing: 0"}
      %tr
        %td{style: "width: 10%; background-color: #e8e8e8"}
        %td{style: "width: 80%; background-color: #FDFEFF"}
          %table{cellpadding: "0", cellspacing: "0",cellpadding: "0", cellspacing: "0",  style: "width: 100%; height: 100%"}
            %tr
              %td{colspan: "3", style: "height: 25%"}

            %tr
              %td{style: "width: 15%;"}
              %td
                %table{cellpadding: "0", cellspacing: "0",style: "width: 100%; height: 100%"}
                  %tr{style: "height: 25%"}
                    %td{style: "background-color: #E8E8E8; border: 1px solid #00929f; width: 93%"}
                      %h1{style: "font-family: Helvetica, Arial, sans-serif; font-size: 24px; color: #244a67; padding-left: 20px"}
                        = yield :head
                        %span{style: "font-weight: normal"}
                          = yield :mail
                  %tr{style: "width: 100%; height: 75%"}
                    %td{style: "border: 1px solid #00929f"}
                      .p_content{style: "font-family: Helvetica, Arial, sans-serif ; font-size: 16px; margin-top: 0px; margin-bottom: 5%; padding: 0px; color: #244a67; padding-left: 20px"}
                        = yield :content
                    %td
              %td{style: "width: 15%;"}
            %tr
              %td{colspan: "3", style: "height: 25%"}

        %td{style: "width: 10%; background-color: #e8e8e8"}